"""add_question_sets_and_missing_schema

Revision ID: 47602d1e9233
Revises: 257b74da89f1
Create Date: 2026-10-01 16:33:37.461277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47602d1e9233'
down_revision: Union[str, Sequence[str], None] = '257b74da89f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('question_set_id', sa.String(length=36), nullable=True))
    op.create_foreign_key('fk_questions_question_set_id', 'questions', 'question_sets', ['question_set_id'], ['id'], ondelete='SET NULL')
    op.add_column('reports', sa.Column('candidate_snapshot', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('reports', sa.Column('summary_pdf_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'summary_pdf_path')
    op.drop_column('reports', 'candidate_snapshot')
    op.drop_constraint('fk_questions_question_set_id', 'questions', type_='foreignkey')
    op.drop_column('questions', 'question_set_id')
    # ### end Alembic commands ###
